sudo: required
dist: trusty
language: bash
script: 
      - wget -q https://sourceforge.net/projects/xiaomi-eu-multilang-miui-roms/files/latest/download -O one.zip
      - unzip one.zip
      - sudo rm -r one.zip
      - wget https://raw.githubusercontent.com/xpirt/sdat2img/master/sdat2img.py
      - chmod +x *
      - ./sdat2img.py system.transfer.list  system.new.dat
      - mkdir output
      - sudo mount -t ext4 -o loop system.img output/
      - sudo rm -r system.new.dat
      - mkdir zip
      - cd output
      - sudo mv * ../zip
      - cd ..
      - cd zip
      - sudo rm -r app/Chrome/Chrome.apk
      - cd app/Chrome
      - sudo touch "removed +100mb.txt"
      - cd ../..
      - sudo zip -r xia.zip -s 1000m *
      - echo .
      - echo .
      - echo .
      - echo .
      - echo .
      - curl --upload-file ./xia.zip https://transfer.sh/xia.zip
      - curl --upload-file ./xia.z01 https://transfer.sh/xia.z01
      - echo .
      - echo .
      - echo .
      - echo .
      - echo .
      - echo done
addons:
  apt:
    packages:
    - zip
    - unzip
    - ncftp
    - p7zip-full
