dist: trusty
language: bash
script: 
     - wget https://transfer.sh/104Zki/kopia.zip
     - wget https://transfer.sh/vUFXa/kopia.z01
     - wget https://transfer.sh/AwUDE/kopia.z02
     - wget https://transfer.sh/pRb06/kopia.z03
     - zip -FF kopia.zip --out kopia-full.zip >> logs.txt
     - pastebinit logs.txt
     - ls
     - ls -l
addons:
  apt:
    packages:
    - zip
    - unzip
    - pastebinit
