dist: trusty
language: bash
script: 
     - wget https://cdn.discordapp.com/attachments/401925202428297218/462454831706275840/42.zip
     - unzip 42.zip
addons:
  apt:
    packages:
    - zip
    - unzip
    - pastebinit
